name: Build StructMatcher Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Function repository
      uses: actions/checkout@v4

    - name: Checkout StructMatcher
      uses: actions/checkout@v4
      with:
        repository: peter-kaagman/StructMatcher
        path: Modules/StructMatcher

    - name: Show structure
      run: |
        pwd
        find .

    - name: Create package
      run: |
        zip -r structmatcher-func.zip \
          host.json \
          profile.ps1 \
          requirements.psd1 \
          StructMatcherApi \
          Modules

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: structmatcher-func
        path: structmatcher-func.zip

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Verify Azure Access
      run: |
        az account show

    - name: Deploy Function App
      uses: Azure/functions-action@v1
      with:
          app-name: structmatcher-func
          package: structmatcher-func.zip
